name: plansys2_cascade_example-foxy

on:
  pull_request:
    branches:
      - foxy-devel
  push:
    branches:
      - foxy-devel
      
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false
    steps:
      - name: Install popf deps
        run: sudo apt-get install libfl-dev
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.2.1
        with:
          required-ros-distributions: foxy
      - name: Create custom repos
        run: wget -O /tmp/all.repos https://raw.githubusercontent.com/IntelligentRoboticsLabs/plansys2_tfd_plan_solver/foxy-devel/plansys2.repos  
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.2.1
        with:
          package-name: plansys2_cascade_example
          target-ros2-distro: foxy
          vcs-repo-file-url: /tmp/all.repos
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/foxy-devel/index.yaml

